package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Accion.java
//  @ Date : 06/05/2022
//  @ Author :
//
//



public class Accion {
    public Grado Grado;

}