package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Alumnos.java
//  @ Date : 19/05/2022
//  @ Author : 
//
//




public class Alumnos extends Observadores {
	private String NumMatricula;

	public Alumnos(String dni, String nombre, String apellido1, String Correo, String apellido2, String contrasenia,String NumMatricula) {
		super(dni, nombre, apellido1, Correo, apellido2, contrasenia);
		this.NumMatricula=NumMatricula;
	}


	public void destroy() {
	
	}

	public String getNumMatricula() {
		return NumMatricula;
	}

	public void setNumMatricula(String numMatricula) {
		NumMatricula = numMatricula;
	}
}
