package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Aula.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//


import java.util.Scanner;

public class Aula implements IAula {
	private String nombreCentro;
	private String idInterno;
	private Integer aforo;
	private Integer tipoAula;
	/*public PDI PDI;
	public Observadores observador;
	public CAula c_Aula;
	public PAS PAS;
	public Elemento elemento;
	public void monitorizarSensores() {
	
	}*/



	@Override
	public void Aula(String nombreCentro, String idInterno, Integer aforo, Integer tipoAula) {
		this.nombreCentro = nombreCentro;
		this.idInterno = idInterno;
		this.aforo = aforo;
		this.tipoAula = tipoAula;
	}

	public String getNombreCentro() {
		return nombreCentro;
	}

	public void setNombreCentro(String nombreCentro) {
		this.nombreCentro = nombreCentro;
	}

	public String getIdInterno() {
		return idInterno;
	}

	public void setIdInterno(String idInterno) {
		this.idInterno = idInterno;
	}

	public Integer getAforo() {
		return aforo;
	}

	public void setAforo(Integer aforo) {
		this.aforo = aforo;
	}

	public Integer getTipoAula() {
		return tipoAula;
	}

	public void setTipoAula(Integer tipoAula) {
		this.tipoAula = tipoAula;
	}

	public void altaAula(){
		Aula aula = new Aula();
		System.out.println("Inserte los datos del aula:\nNombre del centro: ");
		Scanner sc=new Scanner(System.in);
		aula.setNombreCentro(sc.nextLine());
		System.out.println("Identificador Interno: ");
		aula.setIdInterno(sc.nextLine());
		System.out.println("\nAforo maximo: ");
		aula.setAforo(sc.nextInt());
		System.out.println("\nTipo de aula: ");
		aula.setTipoAula(sc.nextInt());

	}

	@Override
	public void destroy() {
	
	}
}
