package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Aula.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//


import java.util.*;

public class Aula implements IAula,ICSubscripcion {
	private String nombreCentro;
	private Long idInterno;
	private Integer aforo;
	private Integer tipoAula;
	private GUI_Subscripcion guiSubscripcion;
	private List<Observadores> observadores = new LinkedList<>();
	private List<Aula> listaAula= new LinkedList<>();
	public CAula c_Aula;
	/*public PDI PDI;
c
	public PAS PAS;
	public Elemento elemento;
	public void monitorizarSensores() {
	
	}*/


	public Aula() {
		guiSubscripcion=new GUI_Subscripcion(this);
	}

	public void Aula(String nombreCentro, Long idInterno, Integer aforo, Integer tipoAula) {
		//llama al constructor (no se pa q )
	}


	public String getNombreCentro() {
		return nombreCentro;
	}

	public void setNombreCentro(String nombreCentro) {
		this.nombreCentro = nombreCentro;
	}

	public Long getIdInterno() {
		return idInterno;
	}

	public void setIdInterno(Long idInterno) {
		this.idInterno = idInterno;
	}

	public Integer getAforo() {
		return aforo;
	}

	public void setAforo(Integer aforo) {
		this.aforo = aforo;
	}

	public Integer getTipoAula() {
		return tipoAula;
	}

	public void setTipoAula(Integer tipoAula) {
		this.tipoAula = tipoAula;
	}

	public void addObservador (Observadores observador) {
		observadores.add(observador);
	}




	public  Aula(String nombreCentro, Long idInterno, Integer aforo, Integer tipoAula) {
		this.nombreCentro = nombreCentro;
		this.idInterno = idInterno;
		this.aforo = aforo;
		this.tipoAula = tipoAula;
	}

	@Override
	public void destroy() {
	
	}

	@Override
	public void subscribirUsuario() {

	}

	public void altaAula(){
		Scanner sc = new Scanner(System.in);
		 String nombreCentro = sc.nextLine();
		 Long idInterno = sc.nextLong();
		 Integer aforo = sc.nextInt();
		 Integer tipoAula = sc.nextInt();
		if((idInterno>0000 && idInterno<5000 )&&!nombreCentro.isEmpty() && (aforo>0)&&(tipoAula==1|| tipoAula == 2 || tipoAula== 3 || tipoAula==4)){
			c_Aula.addAula(new Aula(nombreCentro,idInterno,aforo,tipoAula));
		}
	}

}
