package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CalidadAireSAREF4BLDG.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public class CalidadAireSAREF4BLDG extends Sensores {
	public CalidadAireSAREF4BLDG(String fabricante, Integer numSerie, Integer fecha, String usuario) {
		super(fabricante, numSerie, fecha, usuario);
	}

}
