//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CAula.java
//  @ Date : 19/05/2022
//  @ Author : 
//
//

package org.example;
import java.util.LinkedList;
import java.util.List;

public class CAula implements ICAula {
	private List<Aula> listaAula;
	private GUI_CAula guiCAula;


	public CAula(){
		listaAula = new LinkedList<Aula>();
		guiCAula = new GUI_CAula(this);
	}
	
	public void destroy() {
	
	}
	
	public void obtener(Integer id) {
		listaAula.get(id);
	}

	public void AltaAula(String nombreCentro, Long idInterno, Integer aforo, String tipoAula) {
		if(!nombreCentro.isEmpty()){
			if(idInterno>0000 && idInterno<5000){
				if(aforo>0){
					if(tipoAula=="Teoria" || tipoAula=="Practicas"){
						listaAula.add(new Aula(nombreCentro,idInterno,aforo,tipoAula));
					}
				}
			}
		}
	}
}
