package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CUsuario.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//


import javax.swing.*;

public class CUsuario implements ICUsuario {
	private Usuario usuario;
	private GUI_CUsuario gui;

	public CUsuario() {
		gui=new GUI_CUsuario(this);
	}

	public void CUsuario (String dni, String nombre, String apellidos, String contrasenia) {
		usuario.Usuario(dni,nombre,apellidos,contrasenia);
	}

	public Usuario obtener() {
		return usuario;
	}
	public void getGUI_CUsuario(){};

	public void destroy() {
		usuario.destroy();
	}

    public GUI_CUsuario getGUI() {
		return gui;
    }
}
