package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CUsuario.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public class CUsuario implements ICUsuario {
	private Usuario usuario;

	public void CUsuario (String dni, String nombre, String apellidos, String contrasenia) {
		usuario.Usuario(dni,nombre,apellidos,contrasenia);
	}

	public Usuario obtener() {
		return usuario;
	}

	public void destroy() {
		usuario.destroy();
	}

}
