package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Grado.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public class Grado {
	private String intensidad;
	public void Grado(String intensidad) {
		this.intensidad=intensidad;
	}

	public String getIntensidad() {
		return intensidad;
	}

	public void setIntensidad(String intensidad) {
		this.intensidad = intensidad;
	}
}
