package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GUI_CUsuario.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public class GUI_CUsuario {

    private final ICUsuario controlador;

    public GUI_CUsuario(ICUsuario entrada){
        this.controlador = entrada;

    }

    public void show() {
    }
}
