package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GUI_CAula.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public class GUI_CAula {
    private final ICAula controlador;

    public GUI_CAula(ICAula entrada){
        this.controlador=entrada;
    }

    public void show(){
        System.out.println("hola mundo de 300k");
    }

}
