package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//  @ Project : Untitled
//  @ File Name : GUI_CUsuario.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//


import java.util.Scanner;

public class GUI_CUsuario {

    private final ICUsuario controlador;

    public GUI_CUsuario(ICUsuario entrada) {
        this.controlador = entrada;

    }

    public void show(){

        int var;
        System.out.println("¿Que desea hacer?\n1. Dar de alta un usuario\n2. Suscribircion a un aula: ");
        Scanner sc = new Scanner(System.in);
        var = sc.nextInt();
        switch (var) {
            case 1:
                Usuario user = new Usuario();
                user.altaUsuario();
                break;
            case 2:/*La subscripcion a un aula debe ir en GUI_Subscripcion*/
                System.out.println("Has elegido la opcion 2.");
                break;
        }
    }


}


