//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GUI_Subscripcion.java
//  @ Date : 19/05/2022
//  @ Author : 
//
//

package org.example;
import java.util.Scanner;

public class GUI_Subscripcion {
	private final ICSuscripcion controlador;

	public GUI_Subscripcion (ICSuscripcion entrada){
		this.controlador=entrada;
	}

	public void show(){
		int var;
		System.out.println("¿Que desea hacer?\n1. Dar de alta un aula\n2. Salir");
		Scanner sc= new Scanner(System.in);
		var = sc.nextInt();
		switch (var){
			case 1:
				//controlador.Suscribirse(Usuario usuario);
				break;
			case 2:
				break;
		}
	}
}
