//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GUI_CUsuario.java
//  @ Date : 19/05/2022
//  @ Author : 
//
//

package org.example;
import java.util.Scanner;

public class GUI_CUsuario {
	private final ICUsuario controlador;

	public GUI_CUsuario(ICUsuario entrada) {
		this.controlador=entrada;
	}
	public void show(){
		int var;
		System.out.println("¿Que desea hacer?\n1. Dar de alta un Usuario\n2. Salir");
		Scanner sc= new Scanner(System.in);
		var = sc.nextInt();
		switch (var){
			case 1:
//Pedir que introduzcan datos
				String contrasenia=sc.nextLine();
				String correo=sc.nextLine();
				String apellido2=sc.nextLine();
				String apellido1=sc.nextLine();
				String nombre=sc.nextLine();
				String dni=sc.nextLine();

				controlador.AltaUsuario(dni,nombre,apellido1,apellido2,correo,contrasenia);
			case 2:
				break;
		}
	}
}
