package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GUI_Subscripcion.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//


public class GUI_Subscripcion {

    private Aula controlador;

    public GUI_Subscripcion(Aula controlador){
        this.controlador = controlador;
    }
    private final ICUsuario controlador;
    public GUI_Subscripcion(ICUsuario entrada) {
        this.controlador = entrada;}


    public void show(){
        controlador.addObservador(new Observadores());

    }


}


