package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IAula.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public interface IAula {
	void Aula(String nombreCentro, String idInterno, Integer aforo, Integer tipoAula);
	void destroy();
}
