//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IAula.java
//  @ Date : 19/05/2022
//  @ Author : 
//
//



package org.example;
public interface IAula {
	//void new(String nombreCentro, String idInterno, Integer aforo, Integer tipoAula);
	
	public void destroy() ;
}
