//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ICAula.java
//  @ Date : 19/05/2022
//  @ Author : 
//
//

package org.example;


public interface ICAula {
    void AltaAula(String nombreCentro, Long idInterno, Integer aforo, String tipoAula);
}
