package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ICAula.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public interface ICAula {
    void CAula(String nombreCentro, String idInterno, Integer aforo, Integer tipoAula);
}
