package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ICSuscripcion.java
//  @ Date : 19/05/2022
//  @ Author : 
//
//




public interface ICSuscripcion {
    void Suscribirse(Usuario suscriptor);
}
