package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ICUsuario.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public interface ICUsuario {
    void CUsuario (String dni, String nombre, String apellidos, String contrasenia);
}

