//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ICUsuario.java
//  @ Date : 19/05/2022
//  @ Author : 
//
//
package org.example;



public interface ICUsuario {
    void AltaUsuario (String dni,String nombre, String apellido1, String apellido2, String correo, String contrasenia);
}

