//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IPPDI.java
//  @ Date : 19/05/2022
//  @ Author : 
//
//


package org.example;

public interface IPPDI {
}
