package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IUsuario.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public interface IUsuario {
	void Usuario(String dni, String nombre, String apellidos, String contrasenia);
	String getDNI();
	String getNombre();
	String getApellidos();
	void setDNI(String DNI);
	void setNombre(String nombre);
	void setApellidos(String apellidos);
	void setContrasenia(String contrasenia);
	
	void destroy();
}
