package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IUsuario.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public interface IUsuario {
	void Usuario(String dni, String nombre, String apellidos, String contrasenia);
	
	void destroy();
}
