//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IUsuario.java
//  @ Date : 19/05/2022
//  @ Author : 
//
//

package org.example;


public interface IUsuario {
	//void new(String dni, String nombre, String apellidos, String contrasenia) ;
	
	public void destroy();
}
