package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Observadores.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//


import java.util.ArrayList;

public class Observadores extends Usuario {
	private String elementosContenidos;
	public Aula aulaT;
	private ArrayList aulas;

	public void setElementosContenidos(String elem) {
		this.elementosContenidos=elem;
	}
	
	public String getElementosContenidos() {
		return elementosContenidos;
	}
	
	public void destroy() {
	
	}
}
