//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Observadores.java
//  @ Date : 19/05/2022
//  @ Author : 
//
//
package org.example;

import java.util.List;

public class Observadores extends Usuario {
	private List<Aula> listaAula;

	public Observadores(String dni, String nombre, String apellido1, String Correo, String apellido2, String contrasenia) {
		super(dni, nombre, apellido1, apellido2, contrasenia, Correo);
	}
	public Observadores(Usuario usuario){
		super(usuario.getDNI(),usuario.getNombre(),usuario.getApellido1(),usuario.getApellido2(),usuario.getContrasenia(),usuario.getCorreo());
	}

	public void destroy() {
	
	}
}
