//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PAS.java
//  @ Date : 19/05/2022
//  @ Author : 
//
//

package org.example;


public class PAS extends Usuario {
	private String CodigoPersonal;
	private Integer AnioIncorporacion;
	public Aula AulaD;

	public PAS(String dni, String nombre, String apellido1, String Correo, String apellido2, String contrasenia,Integer AnioIncorporacion,String CodigoPersonal) {
		super(dni, nombre, apellido1, Correo, apellido2, contrasenia);
		this.CodigoPersonal=CodigoPersonal;
		this.AnioIncorporacion=AnioIncorporacion;
	}

	public String getCodigoPersonal() {
		return CodigoPersonal;
	}

	public void setCodigoPersonal(String codigoPersonal) {
		CodigoPersonal = codigoPersonal;
	}

	public Integer getAnioIncorporacion() {
		return AnioIncorporacion;
	}

	public void setAnioIncorporacion(Integer anioIncorporacion) {
		AnioIncorporacion = anioIncorporacion;
	}

	public void destroy() {
	
	}
}
