//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PAula.java
//  @ Date : 19/05/2022
//  @ Author : 
//
//

package org.example;


public class PAula implements IPAula {
}
