package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PAula.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public class PAula implements IPAula {
}
