//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PDI.java
//  @ Date : 19/05/2022
//  @ Author : 
//
//

package org.example;


public class PDI extends Observadores {
	private String CodigoTrabajador;
	private String CategoriaPDI;
	public Aula AulaI;
	//public Actuadores Actuadores;

	public PDI(String dni, String nombre, String apellido1, String Correo, String apellido2, String contrasenia,String CodigoTrabajador, String CategoriaPDI) {
		super(dni, nombre, apellido1, Correo, apellido2, contrasenia);
		this.CodigoTrabajador=CodigoTrabajador;
		this.CategoriaPDI=CategoriaPDI;
	}

	public String getCodigoTrabajador() {
		return CodigoTrabajador;
	}

	public void setCodigoTrabajador(String codigoTrabajador) {
		CodigoTrabajador = codigoTrabajador;
	}

	public String getCategoriaPDI() {
		return CategoriaPDI;
	}

	public void setCategoriaPDI(String categoriaPDI) {
		CategoriaPDI = categoriaPDI;
	}

	public void destroy() {
	
	}
}
