//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PPDI.java
//  @ Date : 19/05/2022
//  @ Author : 
//
//

package org.example;

public class PPDI implements IPPDI {
}
