//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PUsuario.java
//  @ Date : 19/05/2022
//  @ Author : 
//
//

package org.example;


public class PUsuario implements IPUsuario {
}
