package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sensores.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public class Sensores extends DispositivosIot {
	private String tipoSensores;
	public Medidas medidas;

	public Sensores(String fabricante, Integer numSerie, Integer fecha, String usuario) {
		super(fabricante, numSerie, fecha, usuario);
	}

	public void generaMedidas() {

	}

	public void setTipoSensor(String tipo) {
		this.tipoSensores=tipo;
	}
	
	public String getTipoSensor() {
		return tipoSensores;
	}
	
	public void destroy() {
	
	}
}
