package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : System.java
//  @ Date : 06/05/2022
//  @ Author : 
//
//




public class System {
	public void main() {
	
	}
}
