package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TemperaturaOGC.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public class TemperaturaOGC extends Sensores {
	public TemperaturaOGC(String fabricante, Integer numSerie, Integer fecha, String usuario) {
		super(fabricante, numSerie, fecha, usuario);
	}
}
