package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Usuario.java
//  @ Date : 03/05/2022
//  @ Author :
//
//

import java.util.LinkedList;
import java.util.List;
import java.util.Scanner;



public class Usuario implements IUsuario {
	private String DNI;
	private String nombre;
	private String apellidos;
	private String contrasenia;
	public CUsuario cUsuario;
	private List<Usuario> usuarios;

	public void registrarse() {

	}



	@Override
	public void Usuario(String dni, String nombre, String apellidos, String contrasenia) {
		this.DNI=dni;
		this.nombre=nombre;
		this.apellidos=apellidos;
		this.contrasenia=contrasenia;
		this.usuarios = new LinkedList();
	}

	public void cambiarContrasenia(String dniIN) {
		Scanner sc = new Scanner(System.in);
		int cont=0;
		String dniNew;
		cont++;
		if(DNI.equals(dniIN)){
			contrasenia=sc.nextLine();
		}else{
			do{
				System.out.println("El DNI introducido no es correcto");
				dniNew=sc.nextLine();
				if(DNI.equals(dniNew)){
					System.out.println("Introduzca la nueva contraseña: \n");
					contrasenia= sc.nextLine();
				}
			}while(cont<4);
		}

	}

	public String getDNI() {
		return DNI;
	}

	public String getNombre() {
		return nombre;
	}

	public String getApellidos() {
		return apellidos;
	}



	public void setDNI(String DNI) {
		this.DNI = DNI;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public void setContrasenia(String contrasenia) {
		this.contrasenia = contrasenia;
	}

	public void altaUsuario() {
		Scanner sc = new Scanner(System.in);
		int usuario;
		System.out.println("Ha elegido dar de alta un usuario.\n" +
				"Indique si se trata de: \n1. Alumno\n2. PDI\n3. PAS");
		usuario = sc.nextInt();
		switch (usuario) {
			case 1:
				altaAlumno();
				break;
			case 2:
				altaPAS();
				break;
			case 3:
				altaPDI();
				break;
			default:
				System.out.println("Error puta");
		}
	}

	private void altaAlumno() {
		Scanner sc = new Scanner(System.in);
		Alumnos alum = new Alumnos();
		System.out.println("Introduzca los datos en el siguiente order: DNI, nombre, apellidos, numero de matricula y contrasenia: \n");
		alum.setDNI(sc.nextLine());
		alum.setNombre(sc.nextLine());
		alum.setApellidos(sc.nextLine());
		alum.setNumeroMatricula(sc.nextLine());
		alum.setContrasenia(sc.nextLine());
		usuarios.add(alum);
	}

	private void altaPAS(){
		Scanner sc = new Scanner(System.in);
		PAS pas = new PAS();
		System.out.println("Introduzca los datos en el siguiente order: DNI, nombre, apellidos, codigo personal y anio de incorporacion: \n \n");
		pas.setDNI(sc.nextLine());
		pas.setNombre(sc.nextLine());
		pas.setApellidos(sc.nextLine());
		pas.setCodigoPersonal(sc.nextLine());
		pas.setAnioIncorporacion(sc.nextInt());
		usuarios.add(pas);
	}

	private void altaPDI(){
		Scanner sc = new Scanner(System.in);
		PDI pdi = new PDI();
		System.out.println("Introduzca los datos en el siguiente order: DNI, nombre, apellidos, numero de trabajador y categoria PDI: \n");
		pdi.setDNI(sc.nextLine());
		pdi.setNombre(sc.nextLine());
		pdi.setApellidos(sc.nextLine());
		pdi.setCodigoTrabajador(sc.nextLine());
		pdi.setCategoriaPDI(sc.nextLine());
		usuarios.add(pdi);
	}

	@Override
	public void destroy() {

	}
}
