package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Usuario.java
//  @ Date : 19/05/2022
//  @ Author : 
//
//




public class Usuario implements IUsuario {
	private String DNI;
	private String Nombre;
	private String Apellido1;
	private String Apellido2;
	private String Contrasenia;
	private String Correo;
	public CUsuario CUsuario;
	public void registrarse() {
	
	}
	
	public void CambiarContrasenia() {
	
	}

	public Usuario(String DNI, String nombre, String apellido1, String apellido2, String contrasenia, String correo) {
		this.DNI = DNI;
		Nombre = nombre;
		Apellido1 = apellido1;
		Apellido2 = apellido2;
		Contrasenia = contrasenia;
		Correo = correo;
	}

	public String getDNI() {
		return DNI;
	}

	public void setDNI(String DNI) {
		this.DNI = DNI;
	}

	public String getNombre() {
		return Nombre;
	}

	public void setNombre(String nombre) {
		Nombre = nombre;
	}

	public String getApellido1() {
		return Apellido1;
	}

	public void setApellido1(String apellido1) {
		Apellido1 = apellido1;
	}

	public String getApellido2() {
		return Apellido2;
	}

	public void setApellido2(String apellido2) {
		Apellido2 = apellido2;
	}

	public String getContrasenia() {
		return Contrasenia;
	}

	public void setContrasenia(String contrasenia) {
		Contrasenia = contrasenia;
	}

	public String getCorreo() {
		return Correo;
	}

	public void setCorreo(String correo) {
		Correo = correo;
	}

	public void destroy() {
	
	}
}
