package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Actuadores.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public class Actuadores extends DispositivosIot {
	private Boolean actuar;
	private TAccion actuadores;
	public PDI PDI;
	public Accion accion;

	public Actuadores(String fabricante, Integer numSerie, Integer fecha, String usuario) {
		super(fabricante, numSerie, fecha, usuario);
	}

	public void Actuadores(Boolean actuar, TAccion actuadores) {
		this.actuar=actuar;
		this.actuadores=actuadores;
	}
	
	public void setActuar(Boolean actuar) {
		this.actuar=actuar;
	}
	
	public Boolean getActuar() {
		return actuar;
	}

	public TAccion getActuadores() {
		return actuadores;
	}

	public void setActuadores(TAccion actuadores) {
		this.actuadores = actuadores;
	}

	public void destroy() {
	
	}
}
