package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CUsuario.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public class CUsuario implements ICUsuario {
	public Usuario Usuario;
	public void crear(String dni, String nombre, String apellidos, String contrasenia) {
	
	}
	
	public void obtener() {
	
	}
	
	public void destroy() {
	
	}
}
