package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DispositivosIot.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public class DispositivosIot {
	private String fabricante;
	private Integer numSerie;
	private Integer fecha;
	private String usuario;
	public Elemento elemento;

	public DispositivosIot(String fabricante, Integer numSerie, Integer fecha, String usuario) {
		this.fabricante = fabricante;
		this.numSerie = numSerie;
		this.fecha = fecha;
		this.usuario = usuario;
	}

	public String getFabricante() {
		return fabricante;
	}

	public Integer getNumSerie() {
		return numSerie;
	}

	public Integer getFecha() {
		return fecha;
	}

	public String getUsuario() {
		return usuario;
	}

	public void setFabricante(String fabricante) {
		this.fabricante = fabricante;
	}

	public void setNumSerie(Integer numSerie) {
		this.numSerie = numSerie;
	}

	public void setFecha(Integer fecha) {
		this.fecha = fecha;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public void destroy() {
	
	}
}
