package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Elemento.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public class Elemento {
	private Integer numBastidor;
	private TElemento elemento;
	public Medidas medidasA;
	public Aula aulaC;
	public DispositivosIot dispositivoIot;

	public Elemento(Integer numastidor) {
		numBastidor = numastidor;
	}

	public Integer getNumBastidor() {
		return numBastidor;
	}

	public void setNumBastidor(Integer numBastidor) {
		this.numBastidor = numBastidor;
	}

	public TElemento getElemento() {
		return elemento;
	}

	public void setElemento(TElemento elemento) {
		this.elemento = elemento;
	}

	public void destroy() {
	
	}
}
