package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Medidas.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public class Medidas {
	private Integer valor;
	private Integer fecha;
	private String magnitud;
	public Elemento elemento;
	public Sensores sensores;

	public Medidas(Integer valor, Integer fecha, String magnitud) {
		this.valor = valor;
		this.fecha = fecha;
		this.magnitud = magnitud;
	}

	public Integer getValor() {
		return valor;
	}

	public Integer getFecha() {
		return fecha;
	}

	public String getMagnitud() {
		return magnitud;
	}

	public void setValor(Integer valor) {
		this.valor = valor;
	}

	public void setFecha(Integer fecha) {
		this.fecha = fecha;
	}

	public void setMagnitud(String magnitud) {
		this.magnitud = magnitud;
	}

	public void destroy() {
	
	}
}
