package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PAS.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public class PAS extends Usuario {
	private String codigoPersonal;
	private Integer anioIncorporacion;
	public Aula aulaD;

	public PAS(String codigoPersonal, Integer anioIncorporacion) {
		this.codigoPersonal = codigoPersonal;
		this.anioIncorporacion = anioIncorporacion;
	}

	public String getCodigoPersonal() {
		return codigoPersonal;
	}

	public Integer getAnioIncorporacion() {
		return anioIncorporacion;
	}

	public void setCodigoPersonal(String codigoPersonal) {
		this.codigoPersonal = codigoPersonal;
	}

	public void setAnioIncorporacion(Integer anioIncorporacion) {
		this.anioIncorporacion = anioIncorporacion;
	}

	public void destroy() {
	
	}
}
