package org.example;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PObservador.java
//  @ Date : 29/04/2022
//  @ Author : 
//
//




public class PObservador implements IPObservador {
}
