package org.example;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PUsuario.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public class PUsuario implements IPUsuario {
}
