package org.example;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TemperaturaSAREF4BLDG.java
//  @ Date : 03/05/2022
//  @ Author : 
//
//




public class TemperaturaSAREF4BLDG extends Sensores {
	public TemperaturaSAREF4BLDG(String fabricante, Integer numSerie, Integer fecha, String usuario) {
		super(fabricante, numSerie, fecha, usuario);
	}
}
